### ISSUE TITLE
403: Forbidden issue

### ISSUE THREAD

**Issue by mateuszmatu** [pangeo-data/escience-2022#2]
Hi,

I have tried to sign up for an EGI account to get access to the jupyter notebooks for the escience course. I followed the instructions at https://pangeo-data.github.io/escience-2022/before/setup.html, and got emails saying that my requests to join have been approved. 
However, for some reason, when trying to access the jupyter notebook through the link on the setup page, I get redirected to a webpage that gives me an issue 403: forbidden. 
How can I fix this?
-Mateusz

**Comment by sarambl** [comment]
Is this still an issue? This was resolved after some refreshing/logging in and out/waiting for me (not sure what did the trick).

**Comment by sarambl** [comment]
Also, this is the same as this issue: [https://github.com/pangeo-data/escience-2022/issues/1](https://github.com/pangeo-data/escience-2022/issues/1) :)

**Comment by mateuszmatu** [comment]
I'm still having this issue, even after being approved. I tried logging in on both my computer and a different computer, so it does not seem to be a computer issue.

**Comment by annefou** [comment]
It takes a bit of time before being effective.
