### ISSUE TITLE
403 forbidden

### ISSUE THREAD

**Issue by MaherSah** [pangeo-data/escience-2022#4]
Hi,
I cannot login to jupyterHub even though I have followed all the steps from 1 to 4. I get 403 forbidden when it opens that page.
Any help? Am I approved?
Best regards,
maher.

**Comment by annefou** [comment]
It is normal. We need to approve your enrolment and only after you can get access to the JupyterHub. I approved your petitions and you should be able to access it (bear in mind that you may have to clear all cookies, etc.).

**Comment by annefou** [comment]
I close this issue as we have several others with the same topic.
